В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [7]:
import numpy as np
def sigmoid(z):
    return (1 / (1 + np.exp(-z))).round(4)

In [9]:
z_values = np.array([-2, -1, 0, 1, 2])
results = sigmoid(z_values)
for i, z in enumerate(z_values):
    print(f"Sigma function  (z={z}) = {results[i]}")

Sigma function  (z=-2) = 0.1192
Sigma function  (z=-1) = 0.2689
Sigma function  (z=0) = 0.5
Sigma function  (z=1) = 0.7311
Sigma function  (z=2) = 0.8808




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [29]:
def hypothesis(theta, X): 
    return (1 / (1 + np.exp(-np.dot(X, theta)))).round(4)  

In [30]:
theta_values = np.array([0.5, -0.5])
X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])

In [31]:
results_hypothesis = hypothesis(theta_values, X)

In [32]:
results_hypothesis

array([0.3775, 0.7311, 0.6225, 0.5   ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [42]:
 def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)
    return ((1 / m) * np.dot(X.T, (h - y))).round(4)

In [43]:
theta = np.array([0.5, -0.5])
X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])
y = np.array([1, 0, 1, 0])

In [44]:
compute_gradient(theta, X, y)

array([ 0.0578, -0.369 ])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [50]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    theta = np.zeros(X.shape[1])  
    for _ in range(epochs):
        grad = compute_gradient(theta, X, y)
        theta = theta - lr * grad
    return theta.round(4)  

In [51]:
X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])
y = np.array([1, 0, 1, 0])

In [52]:
theta_result = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

In [53]:
theta_result

array([-0.2894,  0.7765])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [60]:
def predict_proba(theta, X):
    return hypothesis(theta, X)

def predict(theta, X, threshold=0.5):
    probabilities = predict_proba(theta, X)
    return (probabilities >= threshold).astype(int)

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

In [61]:
X = np.array([
    [1, 2],
    [1, -1],
    [1, 0],
    [1, 1]
])
y = np.array([1, 0, 1, 0])

In [64]:
theta_result = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)
print("Коефіцієнти theta:", theta_result)

Коефіцієнти theta: [-0.2894  0.7766]


In [68]:
print("5.1. Ймовірності належності до класу 1:")
probabilities = predict_proba(theta_result, X)
for i, prob in enumerate(probabilities):
    print(f"Приклад {i+1}: {prob.round(4)}")

5.1. Ймовірності належності до класу 1:
Приклад 1: 0.7797
Приклад 2: 0.2562
Приклад 3: 0.4282
Приклад 4: 0.6194


In [69]:
print("5.2. Передбачені класи:")
predictions = predict(theta_result, X, threshold=0.5)
for i, pred in enumerate(predictions):
    print(f"Приклад {i+1}: клас {pred}")

5.2. Передбачені класи:
Приклад 1: клас 1
Приклад 2: клас 0
Приклад 3: клас 0
Приклад 4: клас 1


In [73]:
print("5.3. Справжні класи:", y)
print("  Передбачені класи:", predictions)

5.3. Справжні класи: [1 0 1 0]
  Передбачені класи: [1 0 0 1]


In [76]:
print("5.4. Точність моделі:")
acc = accuracy(y, predictions)
print(f"Accuracy = {acc} ({acc*100}%)")

5.4. Точність моделі:
Accuracy = 0.5 (50.0%)


In [80]:
print("Детальний аналіз:")
for i in range(len(y)):
    correct = "+" if y[i] == predictions[i] else "-"
    print(f"Приклад {i+1}: справжній={y[i]}, ймовірність={probabilities[i]:.4f}, передбачений={predictions[i]}, {correct}")

Детальний аналіз:
Приклад 1: справжній=1, ймовірність=0.7797, передбачений=1, +
Приклад 2: справжній=0, ймовірність=0.2562, передбачений=0, +
Приклад 3: справжній=1, ймовірність=0.4282, передбачений=0, -
Приклад 4: справжній=0, ймовірність=0.6194, передбачений=1, -
