### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

In [3]:
vector = np.random.rand(10,)

In [4]:
vector, vector.shape

(array([0.97061402, 0.48766211, 0.46778006, 0.18984253, 0.96384981,
        0.940799  , 0.99536374, 0.26248213, 0.07561466, 0.29293158]),
 (10,))

In [5]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]    
])

In [6]:
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [7]:
vector_2 = (vector + 10).round(2)
vector_2

array([10.97, 10.49, 10.47, 10.19, 10.96, 10.94, 11.  , 10.26, 10.08,
       10.29])

In [8]:
matrix_2 = matrix * 2
matrix_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [9]:
vector_3 = (vector**2).round(2)
vector_3

array([0.94, 0.24, 0.22, 0.04, 0.93, 0.89, 0.99, 0.07, 0.01, 0.09])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [10]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [11]:
#1
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [12]:
#2 
# 2*2 and 2*1 >> 2*1
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [14]:
#3
# 2*2 and 2*2 >> 2*2
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [15]:
#1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [19]:
#2
vector, vector.shape

(array([0.97061402, 0.48766211, 0.46778006, 0.18984253, 0.96384981,
        0.940799  , 0.99536374, 0.26248213, 0.07561466, 0.29293158]),
 (10,))

In [20]:
vector.T, vector.T.shape

(array([0.97061402, 0.48766211, 0.46778006, 0.18984253, 0.96384981,
        0.940799  , 0.99536374, 0.26248213, 0.07561466, 0.29293158]),
 (10,))

Тому що .T не впливає на одномірні масиви в NumPy — лише на дво- або багатовимірні.

In [22]:
#3
column_vector = np.expand_dims(vector, axis=1)

In [24]:
column_vector, column_vector.shape, vector

(array([[0.97061402],
        [0.48766211],
        [0.46778006],
        [0.18984253],
        [0.96384981],
        [0.940799  ],
        [0.99536374],
        [0.26248213],
        [0.07561466],
        [0.29293158]]),
 (10, 1),
 array([0.97061402, 0.48766211, 0.46778006, 0.18984253, 0.96384981,
        0.940799  , 0.99536374, 0.26248213, 0.07561466, 0.29293158]))

Тепер вектор `column_vector` буде (10, 1).

In [26]:
#4
column_vector.T, column_vector.T.shape

(array([[0.97061402, 0.48766211, 0.46778006, 0.18984253, 0.96384981,
         0.940799  , 0.99536374, 0.26248213, 0.07561466, 0.29293158]]),
 (1, 10))

Результат — рядковий вектор з формою (1, 10)